name: Example workflow for Firebase Distribution action
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Get sample .apk for test purposes
        run: wget https://filebin.net/f82qp3youyptbq0w/app-release.apk
      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.4.0
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDS }}
          file: app-release.apk
